name: pyggybank
description: A innovative way of sharing money with friends and your community

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  intro_views_flutter: ^2.8.1
  provider: ^3.2.0
  toast: ^0.1.5
  charts_flutter: ^0.9.0
  barcode_scan: ^3.0.1
  path_provider: 1.1.0
  esys_flutter_share: 1.0.2
  qr_flutter: ^3.0.1
  flutter_slidable: ^0.5.4
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

  assets:
    - assets/images/
    - assets/icons/

